[package]
name = "archetypes"
version = "0.1.0"
edition = "2024"
default-run = "archetypes"

[[bin]]
name = "archetypes"
path = "src/rust/main.rs"

[build-dependencies]
bindgen = "0.72.1"

[dependencies]
chrono = "0.4.42"
